Feature/bs 60 active disable user
fedeveron01/golang-base pull request #34
Opened 2023-10-04 21:28 UTC by angelobenedetti29

2023-10-04 21:37 UTC, fedeveron01 commented on cmd/usecases/user/user_usecase.go
> +}
Por que creaste 2 metodos en el caso de uso ?

2023-10-04 21:38 UTC, fedeveron01 commented on cmd/usecases/user/user_usecase.go
> +	user.ID = uint(id)
Se tendria que borrar esa linea esta de mas

2023-10-04 21:44 UTC, fedeveron01 requested changes

2023-10-04 21:44 UTC, fedeveron01 commented on cmd/adapters/gateways/user_gateway.go
>  func (i *UserGatewayImpl) FindUserByUsernameAndPassword(username string, password string) (entities.User, error) {
No te anda por esto , Cuando llamas al Update del gateway , en el ToServiceEntity te olvidaste de mapear el Active que es lo unico que queres cambiar por eso no se actualiza ese campo

func (i *UserGatewayImpl) ToServiceEntity(user entities.User) gateway_entities.User {
	userDB := gateway_entities.User{
		Model: gorm.Model{
			ID: user.ID,
		},
		UserName: user.UserName,
		Password: user.Password,
                Inactive: user.Inactive
	}
	return userDB
}

2023-10-04 21:44 UTC, fedeveron01 commented on cmd/adapters/gateways/user_gateway.go
>  func (i *UserGatewayImpl) FindUserByUsernameAndPassword(username string, password string) (entities.User, error) {
Tambien habria que revisar el ToBusinessEntitie que se mapee ese campo tambien !

2023-10-04 21:49 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +		p.WriteInternalServerError(w, err)
p.WriteErrorResponse(w, err)

2023-10-04 21:49 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +		p.WriteInternalServerError(w, err)
Si no devolves siempre error 500

2023-10-04 21:51 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	vars := mux.Vars(r)
Antes del vars falta un if mas , hay que validar que sea admin tambien 

`	if !p.IsAdmin(w, r) {
		return
	}`

2023-10-04 21:51 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +// Handle api/user/:id
supongo que no es ese el endpoint

2023-10-04 21:53 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
O sea recibe todo el UserRequest por body ?

podria recibir por url capaz el active true o false

2023-10-04 21:59 UTC, angelobenedetti29 commented on cmd/adapters/gateways/user_gateway.go
>  func (i *UserGatewayImpl) FindUserByUsernameAndPassword(username string, password string) (entities.User, error) {
![image](https://github.com/fedeveron01/factory-management-system-backend/assets/80277100/9bde9d75-9697-416a-8c98-5f0d0b0dcab5)

2023-10-04 22:06 UTC, angelobenedetti29 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
uno el resto de los campos se crean en vacio 
![image](https://github.com/fedeveron01/factory-management-system-backend/assets/80277100/b29b2d7c-fc27-4937-a6af-41f767ddf05a)

2023-10-04 22:07 UTC, angelobenedetti29 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
solo envio ese campo per tengo que castear el resultado en alguna entidad y la uso para eso... estaria mal  ?

2023-10-04 22:08 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
Si , deberias crear otra entidad request

2023-10-04 22:08 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
Despues tenemos que poner que sean obligatorios los campos

2023-10-04 22:10 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
Tendriamos que haber puesto asi los request , en alguna PR hay que hacerlo 

	UserName string	`json:"username" required:"true"`
	Password string `json:"password" required:"true"`

2023-10-04 22:11 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
No hace falta q sea en esa PR pero por eso esta mal que uses ese request

2023-10-04 22:11 UTC, fedeveron01 commented on cmd/adapters/gateways/user_gateway.go
>  func (i *UserGatewayImpl) FindUserByUsernameAndPassword(username string, password string) (entities.User, error) {
si despues subi el commit asi queda

2023-10-05 03:12 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	vars := mux.Vars(r)
Habria que hacer algo aca para que valide que el usuario asociado al token sea != al id a borrar ?

no se si seria en el handler base que tiene acceso al sessionRepository

2023-10-05 03:14 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	err := json.Unmarshal(reqBody, &userRequest)
Hay que crear una entity request para este handler

2023-10-05 03:54 UTC, fedeveron01 commented on cmd/api/mapping.go
> +	app.HandleFunc("/api/user/{id}", handlers.UserHandler.Logout).Methods("PUT")
Eso quedo de mas creo

2023-10-05 03:55 UTC, fedeveron01 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	var InactiveRequest ActiveDesactiveUserRequest
Las variables no se ponen en mayuscula
Trauma de .Net

2023-10-05 12:27 UTC, angelobenedetti29 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	var InactiveRequest ActiveDesactiveUserRequest
sii igual eso es culpa de copilot jajaja

2023-10-05 12:27 UTC, angelobenedetti29 commented on cmd/adapters/entrypoints/handlers/user/handlers.go
> +	var InactiveRequest ActiveDesactiveUserRequest
ahora cuando me pueda hacer un tiempo lo cambio

2023-10-05 17:26 UTC, ebert-alem commented
### Planteo sobre la lógica de la baja usuarios
#### El sistema no puede quedarse sin usuarios...
#### Opciones:
1) Un usuario no se puede auto eliminar, tiene que ser otro usuario administrador que lo haga, así se resolvería que el sistema no se quede sin administradores.

2) Crear un superadmin que no se pueda eliminar 

3) Resolverlo alterando la BD (feo).

En el primer caso se correría el riesgo de que cualquier administrador se quede con el control del sistema el solo, por eso opción 1 y 2 no son excluyentes y podrían combinarse.

Comenten que opinan

2023-10-05 21:45 UTC, fedeveron01 approved these changes

2023-10-05 22:03 UTC, merged